require(devtools)
url <- "https://packagemanager.posit.co/cran/__linux__/noble/2025-08-01"
dependencies <- c("Depends", "Imports", "LinkingTo")
upgrade <- "default"

options(repos = c(CRAN = url))

# CRAN packages w. version
packages <- list(
    "AER",
    "BiocManager",
    "CPBayes",
    "DescTools",
    "EFAtools",
    "GCPBayes",
    "Haplin",
    "MVN",
    "MatrixEQTL",
    "MendelianRandomization",
    "MplusAutomation",
    "PerformanceAnalytics",
    "PooledCohort",
    "PredictABEL",
    "QRISK3",
    "R.matlab",
    "ROCR",
    "RiskScorescvd",
    "argparser",
    "arrow",
    "arsenal",
    "bdsmatrix",
    "bigreadr",
    "bigsnpr",
    "bit",
    "bit64",
    "brant",
    "brms",
    "carat",
    "caret",
    "circlize",
    "coloc",
    "colocPropTest",
    "colocboost",
    "compareC",
    "correlation",
    "corrplot",
    "coxme",
    "data.table",
    "dendextend",
    "dplyr",
    "egg",
    "fastDummies",
    "fastICA",
    "fcfdr",
    "feather",
    "flextable",
    "fmsb",
    "foreign",
    "geepack",
    "genio",
    "ggalluvial",
    "ggcorrplot",
    "ggplot2",
    "ggpubr",
    "ggpubr",
    "ggrepel",
    "ggseg",
    "ggseg3d",
    "ggstar",
    "ggthemes",
    "gitcreds",
    "glmmTMB",
    "glmnet",
    "glue",
    "gplots",
    "gtsummary",
    "here",
    "homologene",
    "ieugwasr",
    "imputeMissings",
    "jtools",
    "kernlab",
    "kinship2",
    "lavaan",
    "lightgbm",
    "lmerTest",
    "magrittr",
    "matlab",
    "matlab2r",
    "matrixStats",
    "mgcv",
    "miniCRAN",
    "mirt",
    "moments",
    "mvtnorm",
    "optparse",
    "pbapply",
    "pROC",
    "parameters",
    "patchwork",
    "pgenlibr",
    "pracma",
    "psych",
    "qqman",
    "r2redux",
    "reghelper",
    "remotes",
    "rjags",
    "rmarkdown",
    "rmatio",
    "rstan",
    "runonce",
    "scales",
    "semTools",
    "semptools",
    "seqminer",
    "simplecolors",
    "simsalapar",
    "sp",
    "splines2",
    "splitstackshape",
    "stringr",
    "survey",
    "survival",
    "survminer",
    "susieR",
    "tibble",
    "tidymodels",
    "tidyr",
    "tree",
    "vctrs",
    "xgboost",
    "zlib")

 
# install package from CRAN and quit with error if installation fails
# for (package in names(packages)) {
for (package in packages) {
    # version <- packages[[package]]

    tryCatch(
    {
        devtools::install_cran(package, dependencies=dependencies, upgrade=upgrade)
    },
    error = function(e) {
        cat("Error occurred during package installation:\n")
        print(e)
        quit(status=1, save="no")
    },
    finally = {
    }
    )
}
