require(devtools)
url <- "https://packagemanager.posit.co/cran/__linux__/focal/2023-02-16"
dependencies <- c('Depends', 'Imports', 'LinkingTo')
upgrade <- 'default'
devtools::install_version('arsenal', version='3.6.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('brant', version='0.3-0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('brms', version='2.18.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('carat', version='2.1.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('circlize', version='0.4.15', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('correlation', version='0.8.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('corrplot', version='0.92', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('CPBayes', version='1.1.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('dendextend', version='1.16.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('fastICA', version='1.2-3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('fcfdr', version='1.0.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('GCPBayes', version='4.0.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('geepack', version='1.3.9', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggalluvial', version='0.12.4', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggcorrplot', version='0.1.4', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggseg', version='1.6.5', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggseg3d', version='1.6.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggstar', version='1.0.4', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggthemes', version='4.2.4', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggpubr', version='0.6.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('gplots', version='3.1.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('homologene', version='1.4.68.19.3.27', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('imputeMissings', version='0.0.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('jtools', version='2.2.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('lavaan', version='0.6-14', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('limma', version='2.10.7', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('lmerTest', version='3.1-3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('MatrixEQTL', version='2.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('mgcv', version='1.8-41', repos=url, dependencies=dependencies, upgrade=upgrade)  # has gamm function
devtools::install_version('miniCRAN', version='0.2.16', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('moments', version='0.14.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('MultiABEL', version='1.1-6', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('MVN', version='5.9', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('patchwork', version='1.1.2', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('pracma', version='2.4.2', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('rjags', version='4-13', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ROCR', version='1.0-11', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('rstan', version='2.21.8', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('semptools', version='0.2.9.6', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('semTools', version='0.5-6', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('simplecolors', version='0.1.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('sp', version='1.6-0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('splines2', version='0.4.7', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('survminer', version='0.4.9', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('tree', version='1.0-43', repos=url, dependencies=dependencies, upgrade=upgrade)

# version=3.12 refs to the Bioconductor version matching our R version
BiocManager::install(c('AnnotationDbi'), version='3.12')
BiocManager::install(c('ASSET'), version='3.12')
BiocManager::install(c('biomaRt'), version='3.12')
BiocManager::install(c('biomartr'), version='3.12')
BiocManager::install(c('clusterProfiler'), version='3.12')
BiocManager::install(c('org.Hs.eg.db'), version='3.12')
BiocManager::install(c('rtracklayer'), version='3.12')
BiocManager::install(c('TMixClust'), version='3.12')

# misc. packages from GitHub
devtools::install_github('alexploner/cfdr.pleio', ref='76d5085e6d3f3ca9576d5d7564d2acf11bcfd021', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('deepchocolate/glm-extras', ref='91f8d53c886b27b7c9941df6c3233f99981323a8', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('jamesliley/cfdr', ref='ec5fddbd27c746a470eb827dc249a80194b231e8', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('jamesliley/cFDR-common-controls', ref='9b923fea283e2373ee8effa2909620a1930004bd', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('MRCIEU/gwasvcf', ref='v0.1.2', repos=url, dependencies=dependencies, upgrade=upgrade)  # inst. before gwasglue
devtools::install_github('MRCIEU/gwasglue', ref='c2d5660eed389e1a9b3e04406b88731d642243f1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('MRCIEU/gwasglue2', ref='5d4e35bad211299e95e25151972382a1d7b84092', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('norment/normentR', ref='dfa1fbae9587db6c3613b0405df4f9cfa98ee0e1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_github('psychgen/phenotools', ref='b744d927a1302d85152917f3802a2212093d588a', repos=url, dependencies=dependencies, upgrade=upgrade)
