version: 2

sphinx:
  configuration: sphinx-docs/source/conf.py

formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: sphinx-docs/source/environment.yml
