# test script checking that all installed libraries are present

library(devtools)
library(rmarkdown)
library(ggplot2)
library(data.table)
library(optparse)
library(foreign)
library(mvtnorm)
library(remotes)
library(survey)
library(BiocManager)
library(qqman)
library(seqminer)
library(rareGWAMA)
library(GenomicSEM)
library(TwoSampleMR)
library(gsmr)
library(snpStats)
