# test script checking that all installed libraries are present

# Load the testthat package
library(testthat)

# List of libraries to check
libraries_to_check <- c(
    "AnnotationDbi",
    "arsenal",
    "ASSET",
    "biomaRt",
    "biomartr",
    "brant",
    "brms",
    "broom",
    "carat",
    "car",
    "cfdr",
    "cfdrCommonControls",
    "cfdr.pleio",
    "circlize",
    "clusterProfiler",
    "correlation",
    "corrplot",
    "CPBayes",
    "DBI",
    "dendextend",
    "e1071",
    "fastICA",
    "fcfdr",
    "foreign",
    "GCPBayes",
    "geepack",
    "ggalluvial",
    "ggcorrplot",
    "ggpubr",
    "ggseg",
    "ggseg3d",
    "ggstar",
    "ggthemes",
    "glmExtras",
    "glmnet",
    "gplots",
    "gridExtra",
    "gwasglue",
    "gwasglue2",
    "gwasvcf",
    "haven",
    "homologene",
    "ieugwasr",
    "imputeMissings",
    "jtools",
    "lavaan",
    "limma",
    "lme4",
    "lmerTest",
    "lubridate",
    "MASS",
    "MatrixEQTL",
    "mgcv",
    "miniCRAN",
    "modelr",
    "moments",
    "MultiABEL",
    "MVN",
    "nlme",
    "normentR",
    "officer",
    "org.Hs.eg.db",
    "parallel",
    "patchwork",
    "phenotools",
    "pracma",
    "psych",
    "RColorBrewer",
    "Rcpp",
    "readxl",
    "readr",
    "rjags",
    "ROCR",
    "RSQLite",
    "rstan",
    "rtracklayer",
    "scales",
    "semptools",
    "semTools",
    "simplecolors",
    "sp",
    "splines",
    "splines2",
    "stats",
    "stats4",
    "survival",
    "survminer",
    "tidyverse",
    "TMixClust",
    "tree",
    "viridis"
)

# Define a test
test_that("Required libraries are installed", {
  missing_libraries <- setdiff(libraries_to_check, installed.packages()[, "Package"])
  expect_true(length(missing_libraries) == 0, 
              sprintf("Missing libraries: %s", paste(missing_libraries, collapse = ", ")))
})