require(devtools)
url <- "https://packagemanager.rstudio.com/cran/__linux__/focal/2023-02-16"
dependencies <- c('Depends', 'Imports', 'LinkingTo')
upgrade <- 'default'
devtools::install_version('argparser', version='0.7.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('bigreadr', version='0.2.5', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('bigsnpr', version='1.11.6', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('BiocManager', version='1.30.19', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('DescTools', version='0.99.47', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('data.table', version='1.14.6', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('dplyr', version='1.1.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('flextable', version='0.8.5', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('fmsb', version='0.7.5', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('ggplot2', version='3.4.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('glue', version='1.6.2', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('gtsummary', version='1.7.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('foreign', version='0.8-84', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('magrittr', version='2.0.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('mvtnorm', version='1.1-3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('optparse', version='1.7.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('pROC', version='1.18.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('qqman', version='0.1.8', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('reghelper', version='1.1.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('remotes', version='2.4.2', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('rmarkdown', version='2.20', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('runonce', version='0.2.3', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('scales', version='1.2.1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('seqminer', version='8.6', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('stringr', version='1.5.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('survey', version='4.1-1', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('tibble', version='3.1.8', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('tidyr', version='1.3.0', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('vctrs', version='0.5.2', repos=url, dependencies=dependencies, upgrade=upgrade)
devtools::install_version('xgboost', version='1.7.3.1', repos=url, dependencies=dependencies, upgrade=upgrade)