devtools::install_version('ggtext', version='0.1.2', repos='https://cloud.r-project.org')
devtools::install_version('janitor', version='2.1.0', repos='https://cloud.r-project.org')
devtools::install_version('haven', version='2.5.1', repos='https://cloud.r-project.org')
devtools::install_version('gtsummary', version='1.7.0', repos='https://cloud.r-project.org')
devtools::install_version('flextable', version='0.8.4', repos='https://cloud.r-project.org')
devtools::install_version('psychometric', version='2.3', repos='https://cloud.r-project.org')
devtools::install_version('effectsize', version='0.8.2', repos='https://cloud.r-project.org')
devtools::install_version('cowplot', version='1.1.1', repos='https://cloud.r-project.org')
devtools::install_version('ggrepel', version='0.9.2', repos='https://cloud.r-project.org')
devtools::install_version('psych', version='2.2.9', repos='https://cloud.r-project.org')
devtools::install_version('jtools', version='2.2.1', repos='https://cloud.r-project.org')
devtools::install_version('MplusAutomation', version='1.1.0', repos='https://cloud.r-project.org')
devtools::install_github("psychgen/phenotools", ref="a602e6513b00f96e33ddff60905c4629f824d44d")
devtools::install_github("norment/normentR", ref="dfa1fbae9587db6c3613b0405df4f9cfa98ee0e1")
