#!/bin/bash
#SBATCH --job-name=gwas
#SBATCH --account=p697_norment
#SBATCH --time=06:00:00
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=8000M


module load singularity/3.7.1

export COMORMENT=/cluster/projects/p697/github/comorment
export SINGULARITY_BIND="$COMORMENT/containers/reference:/REF:ro"
export SIF=$COMORMENT/containers/singularity

export PLINK2="singularity exec --home $PWD:/home $SIF/gwas.sif plink2"
export REGENIE="singularity exec --home $PWD:/home $SIF/gwas.sif regenie"
$REGENIE  --bt --phenoFile run1.pheno --covarFile run1.covar --step 1 --bsize 1000 --out run1.regenie.step1 --bed /REF/examples/regenie/example_3chr --ref-first --bt --lowmem --lowmem-prefix run1.regenie_tmp_preds
