#!/bin/bash
#SBATCH --job-name=gwas
#SBATCH --account=p697_norment
#SBATCH --time=06:00:00
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=8000M


module load singularity/3.7.1

export COMORMENT=/cluster/projects/p697/github/comorment
export SINGULARITY_BIND="$COMORMENT/containers/reference:/REF:ro"
export SIF=$COMORMENT/containers/singularity

export PLINK2="singularity exec --home $PWD:/home $SIF/gwas.sif plink2"
export REGENIE="singularity exec --home $PWD:/home $SIF/gwas.sif regenie"
$PYTHON gwas.py merge-regenie  --sumstats run2_chr@_PHENO.regenie --out run2_PHENO.regenie  --chr2use 1,2,3 
$PYTHON gwas.py merge-regenie  --sumstats run2_chr@_PHENO2.regenie --out run2_PHENO2.regenie  --chr2use 1,2,3 

