name: sphinx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sphinx
  - sphinx_rtd_theme
  - sphinx-design
  - myst-parser
  - make
  - linkify-it-py
  - numpydoc
  - numpy
  - pandas
  - six
  - scipy
  - pyyaml
