# parameters to pass for SLURM jobs
slurm:
  job_name: pgs
  account: p697_norment
  time: "00:30:00"
  cpus_per_task: 2
  mem_per_cpu: 4000MB
  partition: normal

  # list of modules to load in SLURM jobs
  module_load:
    - singularity/3.7.3

# environment variables (edit as necessary)
environ:
  # mandatory root directory containing all inferred directories (edit as necessary).
  # ROOT_DIR: "/cluster/projects/p697/github/comorment"
  ROOT_DIR: "/nrec/space/espenh"

# dependent environment variables (edit as necessary)
# NB: "SIF" is mandatory
environ_inferred:
  # folder containing full clone of https://github.com/comorment/containers
  CONTAINERS: '$ROOT_DIR/containers'
  # reference data within containers repo
  REFERENCE: "$CONTAINERS/reference"
  # directory with singularity containers (.sif files)
  SIF: "$CONTAINERS/singularity"
  # folder containing  full clone of https://github.com/comorment/ldpred2_ref with LDpred2 reference data
  LDPRED2_REF: "$ROOT_DIR/ldpred2_ref"

# for SINGULARITY_BIND variable to set in job scripts
# NB! will be set as "export SINGULARITY_BIND=value0:/key0,value1:/key1,..."
# NB! Also mandatory
SINGULARITY_BIND: 
  REF: '$REFERENCE'
  ldpred2_ref: '$LDPRED2_REF'


## Parameters specific to each PGS calculating tool (refer documentation of each tool):
# Plink
plink:
  clump_p1: 1
  clump_r2: 0.1
  clump_kb: 250
  range_list: [0.001, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 1]
  strat_indep_pairwise: [250, 50, 0.25]
  nPCs: 6
  threads: 4

# PRSice-2
prsice2:
  nPCs: 6
  # base_maf: 0.01
  # base_info: 0.8
  # MAF: 0.01
  # INFO: 0.8
  thread: 4

# LDpred2
ldpred2:
  cores: 4

