name: ci

on:
  push:
    branches:
      - 'espenhgn/issue251'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            comorment/hello:latest
            ghcr.io/comorment/hello:latest
          file: 
            ./docker/dockerfiles/hello/Dockerfile
            ./docker/scripts/apt_get_essential.sh
            ./docker/scripts/install_plink.sh
