# action to build the hello Docker image at each commit without pushing it
name: build hello Docker image

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"

env:
  TEST_TAG: ghcr.io/comorment/hello:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/hello        
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          load: true
          tags: ${{ env.TEST_TAG }}
          file:
            ./dockerfiles/hello/Dockerfile
      - 
        name: Test
        run: |
          pip3 install -r test-requirements.txt
          py.test -v tests/test_hello.py
          docker run --rm -v ${{ github.workspace }}:/home -w /home ${{ env.TEST_TAG }} py.test -v tests/test_hello.py
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          push: False
          tags: ${{ steps.meta.outputs.tags }}
          file:
            ./dockerfiles/hello/Dockerfile
          platforms: linux/amd64
