# action to build and push the python3 Docker and Singularity image at each tag (for release)
name: build & push python3 Docker image

on:
  push:
    tags:
      - "v*.*.*"

env:
  TEST_TAG: ghcr.io/comorment/python3:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/python3        
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          load: true
          tags: ${{ env.TEST_TAG }}
          file:
            ./dockerfiles/python3/Dockerfile
      - name: Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/home -w /home ${{ env.TEST_TAG }} py.test -v tests/test_python3.py
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          file:
            ./dockerfiles/python3/Dockerfile
          platforms: linux/amd64

  build-apptainer-container:
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build Apptainer Container
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0
      - name: Docker meta 
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/python3            
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Apptainer container
        run: |
          tags="${{ steps.meta.outputs.tags }}"
          csv_tags=$(printf "%s\n" "$tags" | awk -F: 'NR==1{printf "%s,", $0; next} {printf "%s,", $NF}' | sed 's/,$//')
          IFS= read -r first_tag <<EOF
          $tags
          EOF
          push_tags="$(printf $csv_tags | sed -e "s/python3/python3_sif/g")"
          echo ${{ secrets.GITHUB_TOKEN }} | oras login --username ${{ github.repository_owner }} --password-stdin ghcr.io
          docker pull kaczmarj/apptainer:latest
          docker run --rm --privileged -v $(pwd):/work kaczmarj/apptainer build python3.sif docker://"$first_tag"
          oras push "$push_tags" --artifact-type application/vnd.acme.rocket.config python3.sif
          rm python3.sif
        shell: sh