# action to build the hello Docker image at each commit without pushing it
name: build hello Docker image

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - 'main'
    paths:
      - 'docker/dockerfiles/hello/Dockerfile'
      - 'docker/scripts/**'
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/containers        
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker"
          push: False
          tags: ${{ steps.meta.outputs.tags }}
          file:
            ./dockerfiles/hello/Dockerfile
          platforms: linux/amd64
